require conf/machine/include/imx93-evk.inc

DDR_FIRMWARE_NAME = " \
   lpddr4_dmem_1d_v202201.bin \
   lpddr4_dmem_2d_v202201.bin \
   lpddr4_imem_1d_v202201.bin \
   lpddr4_imem_2d_v202201.bin \
"

PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-imx"
UBOOT_CONFIG_BASENAME = "imx93_11x11_frdm"
UBOOT_DTB_NAME = "imx93-11x11-frdm"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-imx"
KERNEL_DEVICETREE = "freescale/imx93-11x11-frdm.dtb"
