#!/bin/sh

machine=imx53qsb
eth0.serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=none

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=mnt
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=disk

# boot parameters for SDCard boot
kernel_name=uImage
rootfs_part_linux_dev=mmcblk0p2
rootfs_type=ext3

# can be either 'jffs2' or 'ubifs'
#rootfs_type=ubifs
rootfsimage=rootfs-$machine.$rootfs_type

#kernelimage=zImage-$machine
kernelimage=uImage-$machine.bin
#kernelimage=Image-$machine
#kernelimage=Image-$machine.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/$machine"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

bootargs="console=ttymxc0,115200"

disk_parts="512k(barebox)ro,512k(bareboxenv),8M(kernel),-(root)"

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "
