#!/bin/sh
# -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2014 O.S. Systems Software LTDA.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

usage() {
	cat<<EOF
Usage:

 $0 [ --machine=<machine> ] <path> ...

   <path>
       Directory(ies) where to look for machine definition files.

 Options:

   --machine=<machine>
      Optional param to restrict the printing for a specific machine name.

   --dump
      Generate output in a format which is easier to parse.  Columns
      are separated by TAB.  Empty cells for the "Maintainer" column
      represent "no maintainer".

EOF
}

path=
specific_machine=
dump_mode=

for opt in ${*}; do
    if [ "`echo $opt | cut -b-10`" = "--machine=" ]; then
        specific_machine="`echo $opt | cut -b11-`"
    elif [ "$opt" = "--dump" ]; then
        dump_mode=1
    else
        path="$path $opt"
    fi
done

if [ -z "$path" ]; then
	usage
	exit 1
fi

maintained=`mktemp`
orphan=`mktemp`

machines=`find $path -wholename '*/conf/machine/*.conf'`
for m in $machines; do
	machine=`basename $m | sed 's,\.conf$,,g'`
	if [ -n "$specific_machine" ] && [ "$machine" != "$specific_machine" ]; then
		continue
	fi

	name=`sed -n 's,#@NAME:\s*\(.*\)\s*,\1,p' $m`
	maint=`sed -n 's,#@MAINTAINER:\s*\(.*\)\s*,\1,p' $m`

    if [ -n "$dump_mode" ]; then
	    if [ -n "$maint" ]; then
		    printf "${machine}\t${name}\t${maint}\n" >> $maintained
	    else
		    printf "${machine}\t${name}\n" >> $orphan
	    fi
    else
	    if [ -n "$maint" ]; then
		    printf "%-25s  %-50s  %-50s\n" "$machine" "$name" "$maint" >> $maintained
	    else
		    printf "%-25s  %-50s  %-50s\n" "$machine" "$name" "Orphan" >> $orphan
	    fi
    fi
done

display() {
    sort -u -k 2 $maintained | grep -v $^
    sort -u -k 2 $orphan | grep -v $^
}

if [ -n "$dump_mode" ]; then
    display
else
    cat <<EOF
=========================  ==================================================  ==================================================
         Machine             Name                                               Maintainer
=========================  ==================================================  ==================================================
EOF
    display
    cat <<EOF
=========================  ==================================================  ==================================================
EOF
fi
rm $maintained $orphan
